### ISSUE TITLE
Cannot find interface in other packages

### ISSUE THREAD

**Issue by ldelossa** [josharian/impl#25]
Attempting to use impl from within the go-vim vim plugin. Command seems to fail when trying to find an interface from another package. Is this supported?

Example:

```
  /root
    main.go
    interface.go 
    subpackage/ 
         implementer.go 
```

When I'm in implementer.go I have my mouse over a struct that I want to stub out. I specify the fully qualified name of the root package including the $GOPATH/src path. Tool says unable to find interface in "root.Inteface"

**Comment by josharian** [comment]
That should work. Can you give the exact error message? Can goimports find the package?

**Comment by ldelossa** [comment]
@josharian It was my own fault, I was using quotes. Closing out.

**Comment by josharian** [comment]
Thanks for following up. Guess we should fix https://github.com/josharian/impl/issues/13

**Comment by ldelossa** [comment]
Yes, out of convention I automatically assumed quotes were to be used.
