### ISSUE TITLE
Project Alive?  I'm curious if it's possible to use this with go:generate and redirect to a file.go 

### ISSUE THREAD

**Issue by gcstang** [josharian/impl#26]
I have other things being generated with go:generate and running go generate on the command line but when I try any of these they fail to redirect to a file.

When running these it still just prints to stdout and nothing is in the file.go

Just redirect to file.go
`go:generate impl "l *TransferService" updater.TransferService > file.go`
Redirect out/err to file.go
`go:generate impl "l *TransferService" updater.TransferService 2> file.go 1>&2`

**Comment by josharian** [comment]
Yes, the project is alive, in that people use it and it seems to work fine for them.

If you run the command by itself, does it work as anticipated?

I don't believe that go generate understands redirection.

I don't know why you would want to use go generate with this anyway, though. The whole point is that it generates stubs that you then fill in with actual code.

**Comment by gcstang** [comment]
Thank you for your answers.
Yes it works properly when run by itself.
I thought of using this to start an automation process to build code and using it to create the basics for any implementations before that creation.

**Comment by josharian** [comment]
Makes sense. I wouldn’t use go generate for that, though, just a regular script. I’ll close this for now.
