### ISSUE TITLE
Add TODO comment to each panic line

### ISSUE THREAD

**Issue by philippgille** [josharian/impl#31]
Some editor extensions highlight lines that contain `TODO:` and it's also great for searching code you need to work on (but didn't create an issue yet, or maybe *have* an issue but also want others who browse the code in their IDE and don't know about the ticket see that there's something to do).

So I think it would be creat to not just generate `panic("not implemented")` but:
```
panic("not implemented") // TODO: Implement
```

And in that regard, maybe even change "not implemented" to "not implemented yet", because usually when generating a struct for an interface, you're *going to* implement it.

**Comment by josharian** [comment]
SGTM. I’d personally put the comment on a line by itself preceding the panic.

Or maybe just change it to:

panic(“TODO: implement”)?

**Comment by philippgille** [comment]
I think in case the code gets deployed (either by accident but maybe even as a minimal viable product where the software developer is okay with some functions not being implemented, just a "not implemented yet" would be a better error / panic message than "TODO: implement". The error / panic message should anwer the question "What's wrong?" / "Why did you crash?" and the answer is "not implemented yet".

A panic with "not implemented yet" also mostly resembles what developers might know from other languages, like C#'s `NotImplementedException`, which is for example thrown when you're using .NET Core on a specific platform and call a method that's part of the cross platform .NET Standard, but not (yet) implemented for the specific platform.

Maybe it's a bad analogy to use exceptions and another language and "port" that to Go, but another reason is that I think "TODO: implement" is something like a note by the developer (or in this case the code generation tool) to himself, which fits better as a comment, similar to something like `// Note: This method has to be called here in order to xyz` or `// TODO: Remove this hacky workaround when the used package's bug #123 is fixed`.

So the message is what gets out to the world and the comment is what only the developer sees. And the imperative "TODO: implement" is meant for the developer only.

**Comment by josharian** [comment]
Sure. I don't feel very strongly about it.

I think this should be a very easy fix, just a template update. But it's been years since I thought about this code very much (!).
