### ISSUE TITLE
v1.1.0 release

### ISSUE THREAD

**Issue by qdm12** [josharian/impl#40]
Hi there,

Would you please create a v1.1.0 release (or v1.0.1) to support fixes/features added since December 2020 (https://github.com/josharian/impl/commit/afab9423f121ff77cbe0729726cea5c89749be87)

Thanks!

**Comment by josharian** [comment]
Pushed a tag. If that's not enough, please let me know.

**Comment by qdm12** [comment]
Thanks! Definitely better than using a short commit hash 😄
